_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.5
            "8":
                - 3
                - 5
            "12": 0.19.5
            "13": windows-amd64
batch_size:
    value: 2
dropout:
    value: 0.1
epochs:
    value: 50
input_dim:
    value: 1536
lr:
    value: 0.0001
model_dim:
    value: 512
num_heads:
    value: 8
num_layers:
    value: 2
patience:
    value: 5
